"""herp and derp

Revision ID: 14ad985d103a
Revises: 46ff4b3fe2c7
Create Date: 2013-09-30 01:23:04.311667

"""

# revision identifiers, used by Alembic.
revision = '14ad985d103a'
down_revision = '46ff4b3fe2c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_table', sa.Column('my_derp', sa.Integer(), nullable=True))
    op.add_column('test_table', sa.Column('my_herp', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_table', 'my_herp')
    op.drop_column('test_table', 'my_derp')
    ### end Alembic commands ###
