"""Added states column to congressmember table

Revision ID: 15b681f10782
Revises: 1c981da2b941
Create Date: 2013-10-17 06:59:22.893905

"""

# revision identifiers, used by Alembic.
revision = '15b681f10782'
down_revision = '1c981da2b941'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congressmember', sa.Column('state', sa.String(length=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('congressmember', 'state')
    ### end Alembic commands ###
