"""Base revision

Revision ID: 1c981da2b941
Revises: None
Create Date: 2013-10-17 06:34:44.990722

"""

# revision identifiers, used by Alembic.
revision = '1c981da2b941'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
