"""removed test table

Revision ID: 34698d59bbfb
Revises: 14ad985d103a
Create Date: 2013-10-01 21:24:32.552019

"""

# revision identifiers, used by Alembic.
revision = '34698d59bbfb'
down_revision = '14ad985d103a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'test_table')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'test_table',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'my_column', sa.VARCHAR(), nullable=True),
    sa.Column(u'my_derp', sa.INTEGER(), nullable=True),
    sa.Column(u'my_herp', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
