"""base revision

Revision ID: 4dae864def50
Revises: None
Create Date: 2013-10-04 15:33:16.220529

"""

# revision identifiers, used by Alembic.
revision = '4dae864def50'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
