"""added title column

Revision ID: 56d32c1c0254
Revises: 31838cfbbecb
Create Date: 2013-10-17 07:32:41.721373

"""

# revision identifiers, used by Alembic.
revision = '56d32c1c0254'
down_revision = '31838cfbbecb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congressmember', sa.Column('title', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('congressmember', 'title')
    ### end Alembic commands ###
